### ISSUE TITLE
Crash in forge 1.18.2

### ISSUE THREAD

**Issue by Polarite** [ferriarnus/LiquidBurner#3]
https://paste.tsundereunity.com/uhiyupizen.rb

Happens when imported fluid in the burners, extremely randomly happened on a friends burners, doesnt happen on ours.

**Comment by ferriarnus** [comment]
So uh, that crash is from a different mod. I have made <https://www.curseforge.com/minecraft/mc-mods/liquid-burner>, while your friend seems to be using <https://www.curseforge.com/minecraft/mc-mods/create-liquid-fuel>. It seems this second mod had a similar idea as me though. If you want to use their mod, I would suggest you make an issue on their github <https://github.com/RuochenFu21/CreateLiquidFuel/issues>.

**Comment by Polarite** [comment]
oh shoot, silly friend told me the name as liquid fuel and this one popped up, didnt think there would be the same idea
